# Hyprland keybinds
source = ~/.config/hypr/configs/default_apps.conf

# Variables
$mainMod = SUPER

##############################
# Applications
##############################
bind = $mainMod, Space, exec, $applauncher
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, C, exec, $editor
bind = $mainMod, B, exec, $mainBrowser
bind = $mainMod SHIFT, B, exec, $offBrowser
bind = $mainMod, E, exec, $filemanager
bind = $mainMod SHIFT, E, exec, $g_filemanager

# Utilities
bind = $mainMod, TAB, submap, menu
submap = menu

binde = , Y, exec, $launcher-clipboard
bindl = , Y, submap, reset
binde = , E, exec, $launcher-emojis
bindl = , E, submap, reset
binde = , T, exec, $launcher-translator
bindl = , T, submap, reset
binde = , B, exec, $launcher-bookmarks
bindl = , B, submap, reset

binde = , ESCAPE, submap, reset
binde = , RETURN, submap, reset
submap = reset

bindd = , 107, Screenshot, exec, ~/.config/hypr/scripts/screenshot_area_save # PrtSc: Area and save to file
bindd = $mainMod, 107, Screenshot, exec, ~/.config/hypr/scripts/screenshot_area_copy 
bindd = $mainMod SHIFT, 107, Screenshot, exec, ~/.config/hypr/scripts/screenshot_area_edit

# Others
bind = $mainMod CTRL ALT SHIFT, 49, exec, hyprctl switchxkblayout current next

##############################
# Windows
##############################
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, V, togglefloating,

## Focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

## Moving
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

## Resizing
bind = $mainMod, R, submap, resize
submap = resize
binde = , L, resizeactive, 40 0
binde = , H, resizeactive, -40 0
binde = , K, resizeactive, 0 -40
binde = , J, resizeactive, 0 40
bind = , ESCAPE, submap, reset
submap = reset

##############################
# Workspaces
##############################
## Focus
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1


## Moving
#### Move silently
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8

### Move active window to a workspace
bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, 5, movetoworkspace, 5
bind = $mainMod CTRL, 6, movetoworkspace, 6
bind = $mainMod CTRL, 7, movetoworkspace, 7
bind = $mainMod CTRL, 8, movetoworkspace, 8
