# Wallpaper
exec-once = awww-daemon

exec-once = gnome-keyring-daemon --start --components=secrets

# App launcher
exec-once = vicinae server

# Auto mount
exec-once = udiskie

exec-once = waybar

exec-once = rclone mount drive: ~/Documents/remotes/drive/
exec-once = rclone mount enc: ~/Documents/remotes/enc/
